#! /bin/sh

gap=10
PANEL_HEIGHT=26
export gap
export PANEL_HEIGHT

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding $(($PANEL_HEIGHT -$gap))

bspc config border_width         5
bspc config focused_border_color  "#998e80"
bspc config normal_border_color   "#332f2b"
bspc config urgent_border_color   "#bf9c73"
bspc config presel_feedback_color "#e6e3df"
bspc config window_gap           $gap;

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config paddingless_monocle	 false

bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^1' follow=false state=pseudo_tiled center=true rectangle=1920x1080+740+740
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a jetbrains-pycharm desktop='^2' follow=false
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^8' follow=false
bspc rule -a Slack desktop='^9' follow=false

bash $HOME/.config/polybar/launch.sh bspwm &

feh --bg-fill ~/Pictures/bg.jpg &

dunst -c ~/.config/dunst/dunstrc &
play ~/Music/1-hour-of-silence.mp3 -q repeat 10 &

wmname LG3D

redshift -t 6500:3000 &

export VISUAL='vim -X'
export EDITOR='vim -X'
export TERM=xterm

dropbox start
discord &
slack &


